name: move_music
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  googleapis:
    git:
      url: https://github.com/doodlezucc/googleapis.git
      path: generated/googleapis
  googleapis_auth: any
  spotify: ^0.4.0
  string_similarity: ^1.1.0
  meta: ^1.2.4

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
